const filtersMenuActionTypes = {
    TOGGLE_COLLECTION_LAYOUT: 'TOGGLE_COLLECTION_LAYOUT',
    TOGGLE_FILTERS_PANEL: 'TOGGLE_FILTERS_PANEL',
    TOGGLE_SORT_PANEL: 'TOGGLE_SORT_PANEL',
    TOGGLE_CLEAR_FILTERS_OPTION: 'TOGGLE_CLEAR_FILTERS_OPTION',
    CHANGE_MIN_PRICE_THRESHOLD: 'CHANGE_MIN_PRICE_THRESHOLD',
    CHANGE_MAX_PRICE_THRESHOLD: 'CHANGE_MAX_PRICE_THRESHOLD',
    CHANGE_SORT_RULE: 'CHANGE_SORT_RULE',
};

export default filtersMenuActionTypes;