const filtersMenuActionTypes = {
  TOGGLE_COLLECTION_LAYOUT: 'TOGGLE_COLLECTION_LAYOUT',
  CHANGE_MIN_PRICE_THRESHOLD: 'CHANGE_MIN_PRICE_THRESHOLD',
  CHANGE_MAX_PRICE_THRESHOLD: 'CHANGE_MAX_PRICE_THRESHOLD',
  CHANGE_SORT_RULE: 'CHANGE_SORT_RULE',
};

export default filtersMenuActionTypes;