const filtersMenuActionTypes = {
    TOGGLE_COLLECTION_LAYOUT: 'TOGGLE_COLLECTION_LAYOUT',
    TOGGLE_FILTERS_WINDOW: 'TOGGLE_FILTERS_WINDOW',
    CHANGE_MIN_PRICE_THRESHOLD: 'CHANGE_MIN_PRICE_THRESHOLD',
    CHANGE_MAX_PRICE_THRESHOLD: 'CHANGE_MAX_PRICE_THRESHOLD',
    TOGGLE_CLEAR_FILTERS_OPTION: 'TOGGLE_CLEAR_FILTERS_OPTION',
    CHANGE_SORT_RULE: 'CHANGE_SORT_RULE',

};

export default filtersMenuActionTypes;